CREATE TABLE allplayers (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 clubName VARCHAR(100), name VARCHAR(100), position VARCHAR(100), nationality VARCHAR(50),
 age INTEGER, sex CHAR(1), weight_kg INTEGER, height_cm INTEGER, ratingFifaOverall INTEGER,
 midIssues VARCHAR(255), imagePath VARCHAR(255)
);
CREATE TABLE champions_league_points_table (
 club_id INTEGER PRIMARY KEY, club_name VARCHAR(100), win INTEGER DEFAULT 0, loss INTEGER DEFAULT 0,
 draw INTEGER DEFAULT 0, goal_distributed INTEGER DEFAULT 0, total_points INTEGER DEFAULT 0
);
CREATE TABLE laliga_points_table (
 club_name VARCHAR(100) PRIMARY KEY, win INTEGER DEFAULT 0, loss INTEGER DEFAULT 0,
 draw INTEGER DEFAULT 0, goal_distributed INTEGER DEFAULT 0, total_points INTEGER DEFAULT 0
);
CREATE TABLE club_info (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, club_name VARCHAR(100) NOT NULL,
 strength VARCHAR(100), strength_level VARCHAR(30), weakness VARCHAR(100),
 weakness_level VARCHAR(30), playing_style VARCHAR(100)
);
CREATE TABLE club_statistics (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, club_name VARCHAR(100),
 touches_left_percent INTEGER, touches_middle_percent INTEGER, touches_right_percent INTEGER,
 touches_own_third_percent INTEGER, touches_middle_third_percent INTEGER, touches_opponent_third_percent INTEGER,
 shots_left_percent INTEGER, shots_middle_percent INTEGER, shots_right_percent INTEGER,
 shots_small_box_percent INTEGER, shots_penalty_box_percent INTEGER, shots_outside_box_percent INTEGER,
 against_shots_left_percent INTEGER, against_shots_middle_percent INTEGER, against_shots_right_percent INTEGER,
 against_shots_small_box_percent INTEGER, against_shots_penalty_box_percent INTEGER, against_shots_outside_box_percent INTEGER
);
CREATE TABLE match_statistics (
 matchday INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, match_date DATE, match_time TIME,
 tournament VARCHAR(10) NOT NULL, my_club VARCHAR(100) DEFAULT 'Real Madrid', opponent_club VARCHAR(100) NOT NULL,
 venue VARCHAR(20), stadium VARCHAR(100), my_score INTEGER, opponent_score INTEGER,
 my_goal_scorers CLOB, opponent_goal_scorers CLOB, result VARCHAR(20), my_total_shots INTEGER,
 opponent_total_shots INTEGER, my_shots_on_target INTEGER, opponent_shots_on_target INTEGER,
 my_possession DECIMAL(5,2), opponent_possession DECIMAL(5,2), my_passes INTEGER, opponent_passes INTEGER,
 my_pass_accuracy DECIMAL(5,2), opponent_pass_accuracy DECIMAL(5,2), my_fouls INTEGER,
 opponent_fouls INTEGER, my_yellow_cards INTEGER, opponent_yellow_cards INTEGER,
 my_red_cards INTEGER, opponent_red_cards INTEGER, my_offsides INTEGER, opponent_offsides INTEGER,
 my_corners INTEGER, opponent_corners INTEGER
);
CREATE TABLE playerfifaratings (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100), nationality VARCHAR(50),
 club VARCHAR(100), position VARCHAR(20), overallRating INTEGER, pace INTEGER, shooting INTEGER,
 passing INTEGER, dribbling INTEGER, defending INTEGER, physicality INTEGER, imagePath VARCHAR(255)
);
CREATE TABLE playerperformance (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, clubName VARCHAR(100), playerName VARCHAR(100),
 nationality VARCHAR(50), appearancesTotal INTEGER, appearancesLaLiga INTEGER,
 appearancesChampionsLeague INTEGER, appearancesCopaDelRey INTEGER, appearancesUEFASuperCup INTEGER,
 appearancesNationalTeam INTEGER, goalsTotal INTEGER, goalsLaLiga INTEGER, goalsChampionsLeague INTEGER,
 goalsCopaDelRey INTEGER, goalsUEFASuperCup INTEGER, goalsNationalTeam INTEGER, assistsTotal INTEGER,
 assistsLaLiga INTEGER, assistsChampionsLeague INTEGER, assistsCopaDelRey INTEGER,
 assistsUEFASuperCup INTEGER, manOfTheMatchCount INTEGER, averageRating DOUBLE,
 seasonYear INTEGER, imagePath VARCHAR(255)
);
CREATE TABLE playerstatus (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, playerName VARCHAR(100) NOT NULL,
 playerClub VARCHAR(100) NOT NULL, salary DECIMAL(15,2) NOT NULL, joiningDate DATE NOT NULL,
 leavingDate DATE, playerBonus DECIMAL(15,2) DEFAULT 0, medicalStatus VARCHAR(50) NOT NULL,
 leaveInDate DATE, yellowCardsLAL INTEGER DEFAULT 0, redCardsLAL INTEGER DEFAULT 0,
 yellowCardsUCL INTEGER DEFAULT 0, redCardsUCL INTEGER DEFAULT 0, yellowCardsCDR INTEGER DEFAULT 0,
 redCardsCDR INTEGER DEFAULT 0, yellowCardsUSC INTEGER DEFAULT 0, redCardsUSC INTEGER DEFAULT 0,
 missUpcomingGames INTEGER DEFAULT 0, missLAL INTEGER DEFAULT 0, missUCL INTEGER DEFAULT 0,
 missCDR INTEGER DEFAULT 0, missUSC INTEGER DEFAULT 0, medicalDescription CLOB, imagePath VARCHAR(255)
);
CREATE TABLE training_sessions (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, player_name VARCHAR(100), date DATE,
 session_type VARCHAR(50), attendance_status VARCHAR(20), fitness_level VARCHAR(20), injury_notes CLOB
);
CREATE TABLE transferwindow (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, playerName VARCHAR(100), position VARCHAR(50),
 rating INTEGER, nationality VARCHAR(50), leftClub VARCHAR(100), leftDate DATE,
 joiningClub VARCHAR(100), joiningDate DATE, marketValue DECIMAL(15,2), tradeType VARCHAR(50), imagePath VARCHAR(255)
);

INSERT INTO allplayers(clubName,name,position,nationality,age,sex,weight_kg,height_cm,ratingFifaOverall,midIssues,imagePath) VALUES
('Real Madrid','Kylian Mbappé','ST','France',27,'M',75,178,91,'Fit','images/default.png'),
('Real Madrid','Vinícius Júnior','LW','Brazil',26,'M',73,176,90,'Fit','images/vinicius.png'),
('Real Madrid','Jude Bellingham','CM','England',23,'M',75,186,89,'Fit','images/default.png'),
('Real Madrid','Rodrygo','RW','Brazil',25,'M',64,174,86,'Fit','images/rodrygo.png'),
('Real Madrid','Federico Valverde','CM','Uruguay',28,'M',78,182,88,'Fit','images/default.png'),
('Real Madrid','Luka Modrić','CM','Croatia',40,'M',66,172,85,'Fit','images/modric.png'),
('Real Madrid','Antonio Rüdiger','CB','Germany',33,'M',85,190,86,'Fit','images/rudiger.png'),
('Real Madrid','Eduardo Camavinga','CM','France',23,'M',73,182,85,'Fit','images/default.png'),
('Real Madrid','Éder Militão','CB','Brazil',28,'M',82,186,85,'Fit','images/militao.png'),
('Real Madrid','Thibaut Courtois','GK','Belgium',34,'M',96,199,90,'Fit','images/courtois.png'),
('Real Madrid','Dani Carvajal','RB','Spain',34,'M',74,173,84,'Fit','images/carvajal.png'),
('Real Madrid','Ferland Mendy','LB','France',31,'M',73,180,83,'Fit','images/mendy.png'),
('Barcelona','Robert Lewandowski','ST','Poland',37,'M',81,185,88,'Fit','images/default.png'),
('Barcelona','Pedri','CM','Spain',23,'M',60,174,87,'Fit','images/default.png'),
('Manchester City','Erling Haaland','ST','Norway',26,'M',88,194,91,'Fit','images/default.png'),
('Liverpool','Mohamed Salah','RW','Egypt',34,'M',71,175,89,'Fit','images/default.png');

INSERT INTO laliga_points_table VALUES
('Real Madrid',25,3,5,48,80),('Barcelona',23,5,5,39,74),('Atletico Madrid',20,6,7,30,67),
('Athletic Club',17,8,8,20,59),('Villarreal',16,10,7,15,55),('Real Betis',14,10,9,10,51);
INSERT INTO champions_league_points_table VALUES
(1,'Real Madrid',7,1,0,15,21),(2,'Manchester City',6,1,1,13,19),(3,'Bayern Munich',6,2,0,10,18),
(4,'Barcelona',5,2,1,8,16),(5,'Liverpool',5,3,0,7,15),(6,'PSG',4,3,1,4,13);

INSERT INTO club_info(club_name,strength,strength_level,weakness,weakness_level,playing_style) VALUES
('Barcelona','Possession and midfield control','Very Strong','Defending transitions','Weak','Possession'),
('Manchester City','Pressing and positional play','Very Strong','Space behind defence','Weak','High Press'),
('Bayern Munich','Fast wing attacks','Strong','Counter-press resistance','Weak','Direct Attack'),
('Liverpool','Intensity and transitions','Strong','Defensive spacing','Weak','Gegenpressing');
INSERT INTO club_statistics(club_name,touches_left_percent,touches_middle_percent,touches_right_percent,touches_own_third_percent,touches_middle_third_percent,touches_opponent_third_percent,shots_left_percent,shots_middle_percent,shots_right_percent,shots_small_box_percent,shots_penalty_box_percent,shots_outside_box_percent,against_shots_left_percent,against_shots_middle_percent,against_shots_right_percent,against_shots_small_box_percent,against_shots_penalty_box_percent,against_shots_outside_box_percent) VALUES
('Barcelona',31,42,27,22,48,30,28,46,26,12,61,27,32,39,29,15,56,29),
('Manchester City',29,45,26,18,47,35,25,50,25,14,60,26,30,42,28,13,59,28),
('Bayern Munich',35,35,30,21,43,36,34,38,28,16,58,26,29,40,31,14,57,29),
('Liverpool',32,38,30,24,42,34,31,42,27,13,62,25,34,36,30,16,54,30);

INSERT INTO match_statistics(match_date,match_time,tournament,opponent_club,venue,stadium,my_score,opponent_score,result,my_total_shots,opponent_total_shots,my_shots_on_target,opponent_shots_on_target,my_possession,opponent_possession,my_passes,opponent_passes,my_pass_accuracy,opponent_pass_accuracy,my_fouls,opponent_fouls,my_yellow_cards,opponent_yellow_cards,my_red_cards,opponent_red_cards,my_offsides,opponent_offsides,my_corners,opponent_corners) VALUES
('2025-02-23','20:00:00','SSL','Girona','Home','Santiago Bernabéu',2,0,'Win',17,8,7,2,61,39,612,391,91,84,9,13,1,3,0,0,2,1,8,2),
('2025-03-01','18:30:00','SSL','Real Betis','Away','Benito Villamarín',1,1,'Draw',13,11,5,4,55,45,540,432,89,86,11,12,2,2,0,0,1,2,6,4),
('2025-03-09','21:00:00','SSL','Rayo Vallecano','Home','Santiago Bernabéu',3,1,'Win',19,9,9,3,64,36,650,350,92,81,8,15,1,4,0,0,3,1,9,3),
('2025-04-05','20:00:00','SCDR','Real Sociedad','Home','Santiago Bernabéu',2,1,'Win',16,10,7,4,58,42,580,421,90,85,10,14,2,3,0,0,2,2,7,4),
('2025-06-18','19:00:00','CWC','Al Hilal','Neutral','Hard Rock Stadium',NULL,NULL,'TBD',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('2025-06-22','22:00:00','CWC','Pachuca','Neutral','Bank of America Stadium',NULL,NULL,'TBD',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO playerfifaratings(name,nationality,club,position,overallRating,pace,shooting,passing,dribbling,defending,physicality,imagePath) VALUES
('Kylian Mbappé','France','Real Madrid','ST',91,96,90,83,92,40,78,'images/default.png'),
('Vinícius Júnior','Brazil','Real Madrid','LW',90,95,84,82,93,35,70,'images/vinicius.png'),
('Jude Bellingham','England','Real Madrid','CM',89,82,84,88,88,78,86,'images/default.png'),
('Rodrygo','Brazil','Real Madrid','RW',86,89,82,80,89,38,67,'images/rodrygo.png'),
('Federico Valverde','Uruguay','Real Madrid','CM',88,88,80,86,84,82,87,'images/default.png'),
('Luka Modrić','Croatia','Real Madrid','CM',85,72,76,90,89,62,66,'images/modric.png'),
('Antonio Rüdiger','Germany','Real Madrid','CB',86,82,55,72,70,88,91,'images/rudiger.png'),
('Thibaut Courtois','Belgium','Real Madrid','GK',90,60,45,76,65,91,80,'images/courtois.png');

INSERT INTO playerperformance(clubName,playerName,nationality,appearancesTotal,appearancesLaLiga,appearancesChampionsLeague,appearancesCopaDelRey,appearancesUEFASuperCup,appearancesNationalTeam,goalsTotal,goalsLaLiga,goalsChampionsLeague,goalsCopaDelRey,goalsUEFASuperCup,goalsNationalTeam,assistsTotal,assistsLaLiga,assistsChampionsLeague,assistsCopaDelRey,assistsUEFASuperCup,manOfTheMatchCount,averageRating,seasonYear,imagePath) VALUES
('Real Madrid','Kylian Mbappé','France',45,30,10,4,1,5,38,27,8,2,1,3,8,5,2,1,0,9,8.6,2025,'images/default.png'),
('Real Madrid','Vinícius Júnior','Brazil',43,28,10,4,1,4,24,14,7,2,1,2,15,9,4,2,0,7,8.4,2025,'images/vinicius.png'),
('Real Madrid','Jude Bellingham','England',42,27,10,4,1,5,16,10,4,1,1,2,12,7,3,2,0,6,8.3,2025,'images/default.png'),
('Real Madrid','Rodrygo','Brazil',40,27,9,3,1,3,15,9,4,1,1,1,10,6,3,1,0,4,8.0,2025,'images/rodrygo.png');

INSERT INTO playerstatus(playerName,playerClub,salary,joiningDate,leavingDate,playerBonus,medicalStatus,medicalDescription,imagePath) VALUES
('Kylian Mbappé','Real Madrid',25000000,'2024-07-01','2029-06-30',2000000,'Fit','No medical issues','images/default.png'),
('Vinícius Júnior','Real Madrid',18000000,'2018-07-01','2027-06-30',1500000,'Fit','No medical issues','images/vinicius.png'),
('Jude Bellingham','Real Madrid',20000000,'2023-07-01','2029-06-30',1500000,'Fit','No medical issues','images/default.png'),
('Antonio Rüdiger','Real Madrid',10000000,'2022-07-01','2027-06-30',750000,'Fit','No medical issues','images/rudiger.png'),
('Thibaut Courtois','Real Madrid',14000000,'2018-08-01','2026-06-30',1000000,'Fit','No medical issues','images/courtois.png');

INSERT INTO training_sessions(player_name,date,session_type,attendance_status,fitness_level,injury_notes) VALUES
('Vinícius Júnior','2025-06-04','Tactical','Present','High',''),
('Luka Modrić','2025-06-04','Tactical','Present','Medium',''),
('Rodrygo','2025-06-04','Tactical','Present','High',''),
('Antonio Rüdiger','2025-06-04','Strength','Present','High',''),
('Jude Bellingham','2025-06-05','Cardio','Present','High',''),
('Thibaut Courtois','2025-06-05','Goalkeeping','Present','High','');

INSERT INTO transferwindow(playerName,position,rating,nationality,leftClub,leftDate,joiningClub,joiningDate,marketValue,tradeType,imagePath) VALUES
('Jude Bellingham','Midfielder',89,'England','Borussia Dortmund','2023-06-01','Real Madrid','2023-07-01',120000000,'Permanent','images/default.png'),
('Vinícius Júnior','Forward',90,'Brazil','Flamengo','2018-06-30','Real Madrid','2018-07-01',150000000,'Permanent','images/vinicius.png'),
('Toni Kroos','Midfielder',86,'Germany','Bayern Munich','2014-06-01','Real Madrid','2014-07-01',80000000,'Permanent','images/kroos.png'),
('Kylian Mbappé','Forward',91,'France','PSG','2024-06-30','Real Madrid','2024-07-01',180000000,'Free Transfer','images/default.png'),
('Erling Haaland','Forward',91,'Norway','Manchester City','2026-06-30',NULL,NULL,200000000,'Available','images/default.png'),
('Mohamed Salah','Forward',89,'Egypt','Liverpool','2026-06-30',NULL,NULL,85000000,'Available','images/default.png');
